name: "Python package: build, lint, and test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  build_lint_test:

    env:
      PYTHON_VERSION_COVERAGE_UPLOAD: "3.12"


    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    permissions:
      contents: read

    name: "Python ${{ matrix.python-version }}: build, lint, test"
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package and tooling 
      id: install
      run: |
        python -m pip install "${GITHUB_WORKSPACE}[dev]"

    - name: Lint
      if: ${{ always() && steps.install.conclusion == 'success' }}
      run: |
        make lint

    - name: Test with coverage
      if: ${{ always() && steps.install.conclusion == 'success' }}
      run: |
        make coverage

    - name: Upload coverage artifact
      if: matrix.python-version == env.PYTHON_VERSION_COVERAGE_UPLOAD
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov

    - name: Upload coverage to Codecov
      if: matrix.python-version == env.PYTHON_VERSION_COVERAGE_UPLOAD
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        fail_ci_if_error: false

    - name: Upload coverage artifact
      if: matrix.python-version == env.PYTHON_VERSION_COVERAGE_UPLOAD
      uses: actions/upload-artifact@v4
      with:
        name: ccoverage-report-${{ github.run_id }} 
        path: coverage.xml
